<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<Version>1.0.0.0</Version>
	<Authors>Sangrama Keshari Pattanayak</Authors>
	<Product>BPlusTreeCollection</Product>
	<Description>This is an extended version of IDictionary and created to stote the values in a sorted order using BPlusTree algorithm. Primary aim is to store the data efficiently in a performant way and search will be much quicker. 
Primary aimbition behind creating this, SortedList search will be faster as it uses binary search but inserting data into it is inefficient takes very long. Same way dictionary is very slow in data load and search. Hence BPlusTreeCollection is created to efficiently store the data into it with faster search using binary tree mechanism.</Description>
	<Copyright>OpenSource</Copyright>
	<RepositoryUrl>https://github.com/psangrama/BPlusTreeCollection</RepositoryUrl>
	<RepositoryType>Open Source</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Build\**" />
    <EmbeddedResource Remove="Build\**" />
    <None Remove="Build\**" />
  </ItemGroup>
  
</Project>

